Update RTL guidance documents
rsuite/rsuite.github.io pull request #174
Opened 2020-01-03 05:42 UTC by simonguo

2020-01-03 05:42 UTC, simonguo commented
Deploy preview for *rsuite* processing.

Building with commit efd059a8dd8b142d7c011c36ecf72f7b5efb53ff

https://app.netlify.com/sites/rsuite/deploys/5e0ed43fecda3f0009737608

2020-01-03 11:12 UTC, MohammadYounes requested changes
@simonguo   I believe we should mention the following:

1. Including the RTL version when using the compiled React Suite CSS
 `~rsuite/dist/styles/rsuite-default.rtl.css` or `~rsuite/dist/styles/rsuite-dark.rtl.css`

2. Processing the final CSS via [rtlcss](https://rtlcss.com) in case of using the Less version `~rsuite/lib/styles/themes/default/index.less` or `~rsuite/lib/styles/themes/dark/index.less`

2020-01-03 11:12 UTC, MohammadYounes commented on src/pages/guide/rtl/en/index.md
> +### 3.Post-Processing CSS
@simonguo We already switched to generating full RTL version, The use of bidi version will have some discrepancies and wont work well out of the box. I recommend keeping the officially supported method only.

2020-01-15 07:06 UTC, simonguo commented
@MohammadYounes 
We are refactoring the documentation with Next.js and migrating to the [rsuite](https://github.com/rsuite/rsuite/tree/docs/docs) library.

Then modify the instructions related to rtl.

2022-09-14 01:59 UTC, closed without merging